// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transMessg.proto

#include "transMessg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace transMssg {
PROTOBUF_CONSTEXPR DataPock::DataPock(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.operand_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/0} {}
struct DataPockDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataPockDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataPockDefaultTypeInternal() {}
  union {
    DataPock _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataPockDefaultTypeInternal _DataPock_default_instance_;
}  // namespace transMssg
static ::_pb::Metadata file_level_metadata_transMessg_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_transMessg_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_transMessg_2eproto = nullptr;

const uint32_t TableStruct_transMessg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::transMssg::DataPock, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::transMssg::DataPock, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::transMssg::DataPock, _impl_.value_),
  PROTOBUF_FIELD_OFFSET(::transMssg::DataPock, _impl_.operand_),
  1,
  0,
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, -1, sizeof(::transMssg::DataPock)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::transMssg::_DataPock_default_instance_._instance,
};

const char descriptor_table_protodef_transMessg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020transMessg.proto\022\ttransMssg\"*\n\010DataPoc"
  "k\022\r\n\005value\030\001 \001(\005\022\017\n\007operand\030\002 \001(\t"
  ;
static ::_pbi::once_flag descriptor_table_transMessg_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_transMessg_2eproto = {
    false, false, 73, descriptor_table_protodef_transMessg_2eproto,
    "transMessg.proto",
    &descriptor_table_transMessg_2eproto_once, nullptr, 0, 1,
    schemas, file_default_instances, TableStruct_transMessg_2eproto::offsets,
    file_level_metadata_transMessg_2eproto, file_level_enum_descriptors_transMessg_2eproto,
    file_level_service_descriptors_transMessg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_transMessg_2eproto_getter() {
  return &descriptor_table_transMessg_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_transMessg_2eproto(&descriptor_table_transMessg_2eproto);
namespace transMssg {

// ===================================================================

class DataPock::_Internal {
 public:
  using HasBits = decltype(std::declval<DataPock>()._impl_._has_bits_);
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_operand(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

DataPock::DataPock(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:transMssg.DataPock)
}
DataPock::DataPock(const DataPock& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  DataPock* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.operand_){}
    , decltype(_impl_.value_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.operand_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.operand_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_operand()) {
    _this->_impl_.operand_.Set(from._internal_operand(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.value_ = from._impl_.value_;
  // @@protoc_insertion_point(copy_constructor:transMssg.DataPock)
}

inline void DataPock::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.operand_){}
    , decltype(_impl_.value_){0}
  };
  _impl_.operand_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.operand_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

DataPock::~DataPock() {
  // @@protoc_insertion_point(destructor:transMssg.DataPock)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void DataPock::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.operand_.Destroy();
}

void DataPock::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void DataPock::Clear() {
// @@protoc_insertion_point(message_clear_start:transMssg.DataPock)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.operand_.ClearNonDefaultToEmpty();
  }
  _impl_.value_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* DataPock::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional int32 value = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_value(&has_bits);
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional string operand = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_operand();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          #ifndef NDEBUG
          ::_pbi::VerifyUTF8(str, "transMssg.DataPock.operand");
          #endif  // !NDEBUG
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* DataPock::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:transMssg.DataPock)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional int32 value = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_value(), target);
  }

  // optional string operand = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_operand().data(), static_cast<int>(this->_internal_operand().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "transMssg.DataPock.operand");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_operand(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:transMssg.DataPock)
  return target;
}

size_t DataPock::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:transMssg.DataPock)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    // optional string operand = 2;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_operand());
    }

    // optional int32 value = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_value());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData DataPock::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    DataPock::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*DataPock::GetClassData() const { return &_class_data_; }


void DataPock::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<DataPock*>(&to_msg);
  auto& from = static_cast<const DataPock&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:transMssg.DataPock)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_operand(from._internal_operand());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.value_ = from._impl_.value_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void DataPock::CopyFrom(const DataPock& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:transMssg.DataPock)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DataPock::IsInitialized() const {
  return true;
}

void DataPock::InternalSwap(DataPock* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.operand_, lhs_arena,
      &other->_impl_.operand_, rhs_arena
  );
  swap(_impl_.value_, other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata DataPock::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_transMessg_2eproto_getter, &descriptor_table_transMessg_2eproto_once,
      file_level_metadata_transMessg_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace transMssg
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::transMssg::DataPock*
Arena::CreateMaybeMessage< ::transMssg::DataPock >(Arena* arena) {
  return Arena::CreateMessageInternal< ::transMssg::DataPock >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
