// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transMessg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_transMessg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_transMessg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_transMessg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_transMessg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_transMessg_2eproto;
namespace transMssg {
class DataPock;
struct DataPockDefaultTypeInternal;
extern DataPockDefaultTypeInternal _DataPock_default_instance_;
}  // namespace transMssg
PROTOBUF_NAMESPACE_OPEN
template<> ::transMssg::DataPock* Arena::CreateMaybeMessage<::transMssg::DataPock>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace transMssg {

// ===================================================================

class DataPock final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:transMssg.DataPock) */ {
 public:
  inline DataPock() : DataPock(nullptr) {}
  ~DataPock() override;
  explicit PROTOBUF_CONSTEXPR DataPock(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DataPock(const DataPock& from);
  DataPock(DataPock&& from) noexcept
    : DataPock() {
    *this = ::std::move(from);
  }

  inline DataPock& operator=(const DataPock& from) {
    CopyFrom(from);
    return *this;
  }
  inline DataPock& operator=(DataPock&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DataPock& default_instance() {
    return *internal_default_instance();
  }
  static inline const DataPock* internal_default_instance() {
    return reinterpret_cast<const DataPock*>(
               &_DataPock_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(DataPock& a, DataPock& b) {
    a.Swap(&b);
  }
  inline void Swap(DataPock* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DataPock* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DataPock* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DataPock>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const DataPock& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const DataPock& from) {
    DataPock::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DataPock* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "transMssg.DataPock";
  }
  protected:
  explicit DataPock(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOperandFieldNumber = 2,
    kValueFieldNumber = 1,
  };
  // optional string operand = 2;
  bool has_operand() const;
  private:
  bool _internal_has_operand() const;
  public:
  void clear_operand();
  const std::string& operand() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_operand(ArgT0&& arg0, ArgT... args);
  std::string* mutable_operand();
  PROTOBUF_NODISCARD std::string* release_operand();
  void set_allocated_operand(std::string* operand);
  private:
  const std::string& _internal_operand() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_operand(const std::string& value);
  std::string* _internal_mutable_operand();
  public:

  // optional int32 value = 1;
  bool has_value() const;
  private:
  bool _internal_has_value() const;
  public:
  void clear_value();
  int32_t value() const;
  void set_value(int32_t value);
  private:
  int32_t _internal_value() const;
  void _internal_set_value(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:transMssg.DataPock)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr operand_;
    int32_t value_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_transMessg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DataPock

// optional int32 value = 1;
inline bool DataPock::_internal_has_value() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool DataPock::has_value() const {
  return _internal_has_value();
}
inline void DataPock::clear_value() {
  _impl_.value_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t DataPock::_internal_value() const {
  return _impl_.value_;
}
inline int32_t DataPock::value() const {
  // @@protoc_insertion_point(field_get:transMssg.DataPock.value)
  return _internal_value();
}
inline void DataPock::_internal_set_value(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.value_ = value;
}
inline void DataPock::set_value(int32_t value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:transMssg.DataPock.value)
}

// optional string operand = 2;
inline bool DataPock::_internal_has_operand() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool DataPock::has_operand() const {
  return _internal_has_operand();
}
inline void DataPock::clear_operand() {
  _impl_.operand_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& DataPock::operand() const {
  // @@protoc_insertion_point(field_get:transMssg.DataPock.operand)
  return _internal_operand();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void DataPock::set_operand(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.operand_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:transMssg.DataPock.operand)
}
inline std::string* DataPock::mutable_operand() {
  std::string* _s = _internal_mutable_operand();
  // @@protoc_insertion_point(field_mutable:transMssg.DataPock.operand)
  return _s;
}
inline const std::string& DataPock::_internal_operand() const {
  return _impl_.operand_.Get();
}
inline void DataPock::_internal_set_operand(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.operand_.Set(value, GetArenaForAllocation());
}
inline std::string* DataPock::_internal_mutable_operand() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.operand_.Mutable(GetArenaForAllocation());
}
inline std::string* DataPock::release_operand() {
  // @@protoc_insertion_point(field_release:transMssg.DataPock.operand)
  if (!_internal_has_operand()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.operand_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.operand_.IsDefault()) {
    _impl_.operand_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void DataPock::set_allocated_operand(std::string* operand) {
  if (operand != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.operand_.SetAllocated(operand, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.operand_.IsDefault()) {
    _impl_.operand_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:transMssg.DataPock.operand)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace transMssg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_transMessg_2eproto
